#include "harness_start.bash"

# A consumer compiles with flags that reached it through a
# subproject's .pc file: pconfigure expands the ppkg-config backtick
# once, at configure time, and writes the answer into the Makefile.
# The subproject then ships a new flag in that same .pc -- the exported
# flag changed -- and the built copy of the .pc is regenerated by an
# ordinary make rule, but nothing else in the build reads it: the .pc
# is an input to the configure-time expansion, and it is nobody's
# file dependency.  The consumer keeps yesterday's flags (taxonomy
# types 3, 5, D).
#
# The assertions below spell the correct incremental behavior out and
# are not weakened: after the .pc changes, plain make must leave a
# binary that answers with the new flag.  Against today's pconfigure
# this test fails, on purpose.

mkdir -p src sub/src

cat >Configfile <<EOF
SUBPROJECTS += sub

LANGUAGES   += c

BINARIES    += app
COMPILEOPTS += \`ppkg-config sub --cflags\`
LINKOPTS    += \`ppkg-config sub --libs\`
SOURCES     += app.c
EOF

cat >sub/Configfile <<EOF
LANGUAGES += c
LANGUAGES += h
LANGUAGES += pkgconfig

HEADERSRC += sub.h

LIBRARIES += libsub.so
SOURCES   += sub.c

LIBRARIES += pkgconfig/sub.pc
SOURCES   += sub.pc
EOF

cat >sub/src/sub.pc <<EOF
prefix=@@pconfigure_prefix@@
libdir=\${prefix}/@@pconfigure_libdir@@
includedir=\${prefix}/@@pconfigure_hdrdir@@

Name: sub
Description: a subproject
Version: 1.0
Libs: -L\${libdir} -lsub
Cflags: -I\${includedir} -DANSWER=9
EOF

cat >sub/src/sub.h <<EOF
int sub(void);
EOF

cat >sub/src/sub.c <<EOF
int sub(void) { return 7; }
EOF

cat >src/app.c <<EOF
#include <sub.h>
#include <stdio.h>
int main(void) { printf("%d\n", sub() + ANSWER); return 0; }
EOF

$PTEST_BINARY $PCONFIGURE_ARGS
cat Makefile
make $MAKE_ARGS > first.out 2>&1
cat first.out

# 7 out of the library and 9 out of the .pc's -DANSWER: the exported
# flags really did flow into what the consumer was compiled with.
test "$(./bin/app)" = "16"
grep -q -- "-DANSWER=9" Makefile

# A build with nothing to do is the ordinary answer from here on,
# which is what makes the build after the edit mean something.
make $MAKE_ARGS > settled.out 2>&1
cat settled.out
grep -q "Nothing to be done" settled.out

##############################################################################
# The subproject's exported flags change                                     #
##############################################################################
sleep 2
sed -i 's/-DANSWER=9/-DANSWER=13/' sub/src/sub.pc

make $MAKE_ARGS > second.out 2>&1
cat second.out

# The subproject's built .pc was regenerated out of the new source --
# that part is an ordinary make file dependency and works.
grep -q -- "-DANSWER=13" sub/obj/pkgconfig/sub.pc

# The consumer, which gets its compile flags out of that .pc, picked
# the new flag up: 7 + 13 = 20.  Unweakened -- and failing against
# today's pconfigure, which has nothing in its Makefile depending on
# the .pc, so the consumer is neither recompiled nor relinked and
# keeps answering 16.
test "$(./bin/app)" = "20"

exit 0
