/*
 * Copyright (C) 2015 Palmer Dabbelt
 *   <palmer@dabbelt.com>
 *
 * This file is part of pconfigure.
 * 
 * pconfigure is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * pconfigure is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with pconfigure.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "pkgconfig.h++"
#include "../commands.h++"
#include "../language_list.h++"
#include <assert.h>
#include <iostream>
#include <stdlib.h>
#include <unistd.h>

/* Where this project sits, spelled from the root of the filesystem.
 *
 * The pkg-config file that gets written for the build tree has to say
 * where things are in a way that means the same thing to everybody
 * who reads it, and the projects reading it are at all sorts of
 * depths.  A relative answer would be re-rooted a second time by
 * whoever consumed it. */
static std::string absolute_base(const std::string& base)
{
    auto buffer = std::vector<char>(4096);
    while (getcwd(&buffer[0], buffer.size()) == NULL) {
        if (errno != ERANGE) {
            perror("Unable to find the working directory");
            abort();
        }
        buffer.resize(buffer.size() * 2);
    }

    auto out = std::string(&buffer[0]);
    if (base.size() > 0)
        out += "/" + base.substr(0, base.size() - 1);
    return out;
}

language_pkgconfig* language_pkgconfig::clone(void) const
{
    return new language_pkgconfig(this->list_compile_opts(),
                                  this->list_link_opts());
}

bool language_pkgconfig::can_process(const context::ptr& ctx) const
{
    switch (ctx->type) {
    case context_type::DEFAULT:
    case context_type::GENERATE:
    case context_type::HEADER:
    case context_type::BINARY:
    case context_type::SOURCE:
    case context_type::TEST:
    case context_type::PHONY:
        return false;

    case context_type::LIBRARY:
        return language::all_sources_match(ctx, {".pc"});
    }

    std::cerr << "Internal error: bad context type "
              << std::to_string(ctx->type)
              << "\n";
    abort();
}

std::vector<makefile::target::ptr>
language_pkgconfig::targets(const context::ptr& ctx) const
{
    assert(ctx != NULL);

    switch (ctx->type) {
    case context_type::DEFAULT:
    case context_type::GENERATE:
    case context_type::BINARY:
    case context_type::SOURCE:
    case context_type::TEST:
    case context_type::HEADER:
    case context_type::PHONY:
        std::cerr << "Unimplemented context type: "
                  << std::to_string(ctx->type)
                  << "\n";
        std::cerr << ctx->as_tree_string("  ");
        abort();
        break;

    case context_type::LIBRARY:
    {
        /* BASH-like languages are designed to be super simple: since
         * all they do is just link all the sources together at the
         * end, there's no need for any internal targets at all. */
        auto target = ctx->lib_dir + "/" + ctx->cmd->data();

        auto short_cmd = "PKGCFG\t" + ctx->cmd->data();

        auto sources = std::vector<makefile::target::ptr>();
        for (const auto& child: ctx->children) {
            if (child->type == context_type::SOURCE) {
                auto path = child->src_dir + "/" + child->cmd->data();
                sources.push_back(std::make_shared<makefile::target>(path));
            }
        }

        /* pkg-config can take an indirect sed reference, which
         * involves running a sed command that is stored in a file.
         * Thus, the result of the pkg-config file that is output
         * depends on the contents of that file (which is often
         * generated by pconfigure somewhere else, but that doesn't
         * matter). */
        /* A "-S" names a file that holds a sed command, which is
         * usually generated somewhere else in the same project -- so
         * it's a source of this .pc file, and it's relative to
         * whoever wrote it rather than to where pconfigure ran. */
        auto sed_file = [&](const std::string& str) {
            auto path = str.substr(2);
            if (path.size() > 0 && path[0] != '/')
                return ctx->base + path;
            return path;
        };

        for (const auto& str: this->clopts(ctx))
            if (strncmp(str.c_str(), "-S", 2) == 0)
                sources.push_back(
                    std::make_shared<makefile::target>(sed_file(str)));

        auto global_targets = std::vector<makefile::global_targets>{
            makefile::global_targets::ALL,
            makefile::global_targets::CLEAN,
        };

        auto build = [&](const std::string& prefix) {
            auto command = std::string();
            command += "cat " + sources[0]->name();
            command += " | sed 's^@@pconfigure_prefix@@^" + prefix + "^g'";
            command += " | sed 's^@@pconfigure_libdir@@^" + ctx->unbased(ctx->lib_dir) + "^g'";
            command += " | sed 's^@@pconfigure_hdrdir@@^" + ctx->unbased(ctx->hdr_dir) + "^g'";
            for (const auto& str: this->clopts(ctx)) {
                if (strncmp(str.c_str(), "-S", 2) == 0)
                    command += " | sed `cat " + sed_file(str) + "`";
                else if (strncmp(str.c_str(), "`", 1) == 0)
                    command += " | sed " + str;
                else
                    command += " | sed '" + str + "'";
            }

            command += "> ";
            return command;
        };

        auto command = build(ctx->prefix);

        auto commands = std::vector<std::string>{
            "mkdir -p $(dir $@)",
            command + target
        };

        auto filename = ctx->cmd->debug()->filename();
        auto lineno = ctx->cmd->debug()->line_number();
        auto comment = std::vector<std::string>{
            "language_pkgconfig::targets()",
            filename + ":" + std::to_string(lineno)
        };

        auto bin_target = std::make_shared<makefile::target>(target,
                                                             short_cmd,
                                                             sources,
                                                             global_targets,
                                                             commands,
                                                             comment);

        /* The one above describes where this library will be once
         * it's installed.  Another project in this build needs to
         * link against it now, where it actually is, so there's a
         * second copy that says that -- and it gets built while
         * pconfigure is still running, because the Configfile that
         * wants to know about it is being read right now. */
        auto pkgconfig_dir = ctx->obj_dir + "/pkgconfig";
        auto basename = ctx->cmd->data().substr(
            ctx->cmd->data().find_last_of("/") + 1);
        auto build_path = pkgconfig_dir + "/" + basename;
        auto build_command = build(absolute_base(ctx->base));

        auto build_target = std::make_shared<makefile::target>(
            build_path,
            short_cmd,
            sources,
            std::vector<makefile::global_targets>{
                makefile::global_targets::ALL,
                makefile::global_targets::CLEAN,
            },
            std::vector<std::string>{
                /* Spelled out rather than "$(dir $@)", because these
                 * same commands get run below by pconfigure itself,
                 * where there's no make around to say what that
                 * means. */
                "mkdir -p " + pkgconfig_dir,
                build_command + build_path
            },
            comment);

        add_pkgconfig_path(pkgconfig_dir);

        if (access(build_path.c_str(), R_OK) != 0) {
            auto have_sources = true;
            for (const auto& source: sources)
                if (access(source->name().c_str(), R_OK) != 0)
                    have_sources = false;

            /* Anything it's built from that isn't there yet will be
             * by the time make runs, so this is worth trying and not
             * worth failing over. */
            if (have_sources == true)
                for (const auto& cmd: build_target->cmds())
                    if (system(cmd.c_str()) != 0)
                        break;
        }

        auto install_path = "$(DESTDIR)/" + ctx->prefix + "/" + ctx->unbased(target);

        auto install_commands = std::vector<std::string>{
            "mkdir -p $(dir $@)",
            command + install_path
        };

        auto install_global_targets = std::vector<makefile::global_targets>{
            makefile::global_targets::INSTALL,
            makefile::global_targets::UNINSTALL,
        };

        auto ins_target = std::make_shared<makefile::target>(install_path,
                                                             short_cmd,
                                                             sources,
                                                             install_global_targets,
                                                             install_commands,
                                                             comment);

        return {bin_target, build_target, ins_target};
        break;
    }
    }

    std::cerr << "context type not in switch\n";
    abort();
}

static void install_pkgconfig(void) __attribute__((constructor));
void install_pkgconfig(void)
{
    language_list::global_add(
        std::make_shared<language_pkgconfig>(
            std::vector<std::string>{},
            std::vector<std::string>{}
        )
    );
}
